### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by BLAST1718** [alvin0319/CustomItemLoader#11]
Make a thing like :

```yaml
items:
  ARMOR:
    facebook:
      id: 1001
      meta: 0
      namespace: "custom:facebook"
      name: facebook
      allow_off_hand: true
      max_stack_size: 64
      texture: facebook
      durable: false
      max_durability: 64
      mining_speed: 10
  SWORD:
    facebook:
      id: 1001
      meta: 0
      namespace: "custom:facebook"
      name: facebook
      allow_off_hand: true
      max_stack_size: 64
      texture: facebook
      durable: false
      max_durability: 64
      mining_speed: 10
```
