### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by GamerMJay** [alvin0319/CustomItemLoader#129]
Hello, I wanted to ask why the pickaxe does not degrade faster and it is like the hand?

items:
  PIXEL Pickaxe:
    id: 10000
    meta: 0
    namespace: "custom:pixel_pickaxe"
    texture: "pixel_pickaxe"
    mining_speed: 10
    max_stack_size: 1
    tool_type: 8
    tool_tier: 5 # This will make this tool's tier as Diamond, replace it as you want
    tool: true
    add_creative_inventory: true
    durable: true
    max_durability: 1000

**Comment by alvin0319** [comment]
```yml
items:
  PIXEL Pickaxe:
    id: 10000
    meta: 0
    namespace: "custom:pixel_pickaxe"
    texture: "pixel_pickaxe"
    mining_speed: 10
    max_stack_size: 1
    tool_type: 8
    tool_tier: 5 # This will make this tool's tier as Diamond, replace it as you want
    tool: true
    add_creative_inventory: true
    durable: true
    max_durability: 1000
    dig:
      block_tags: [stone, metal, rail, ] #https://github.com/alvin0319/CustomItemLoader/blob/master/src/alvin0319/CustomItemLoader/item/properties/component/DiggerComponent.php#L34-L58
      speed: 10
```

Replace block tags and speed as your need.
