### ISSUE TITLE
nvalidArgumentException: "Failed to register item: Alias "facebook" is already registered

### ISSUE THREAD

**Issue by royaljacques** [alvin0319/CustomItemLoader#82]
error log 
```log
[Server thread/CRITICAL]: InvalidArgumentException: "Failed to register item: Alias "facebook" is already registered" (51) in "plugins/CustomItemLoader-master/src/alvin0319/CustomItemLoader/CustomItemManager" at line 130
--- Stack trace ---
  #0 plugins/CustomI
```
config: 
```yml
items:
  facebook:
    id: 2000
    meta: 0
    namespace: "custom:facebook"
    name: facebook
    allow_off_hand: true
    max_stack_size: 64
    texture: stick
    durable: false
    max_durability: 64
    mining_speed: 10
    food: true
    can_always_eat: true
    nutrition: 10
    saturation: 2
```
